### ISSUE TITLE
Hide read post 

### ISSUE THREAD

**Issue by SocialSavvy** [idunnololz/summit-for-lemmy#1]
Hello first star and first issues 😃🎊

I really want you to put a feature in the next version. I don't know if it's too hard for you to do that. However, it will reveal its difference from other applications. It's really annoying to see the same content over and over again. Can you add a show read post/hide read post setting to the section in the picture?
![Screenshot_20230703-104635_Summit.jpg](https://github.com/idunnololz/summit-for-lemmy/assets/107673019/a7d98603-5737-4e25-9ae9-2a4d5ed682f1)

**Comment by SocialSavvy** [comment]
Or you can add fab button this settings

**Comment by idunnololz** [comment]
Fix a while ago.
