### ISSUE TITLE
Predictive Back Support

### ISSUE THREAD

**Issue by metronidazole** [idunnololz/summit-for-lemmy#10]
First of all, thanks for making a great app. I found your lemmy client to be the most usable and feature-filled of all the ones I tried.

Could you please add predictive back support as detailed in https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture

It really improves animation and flow when navigating within an app.

**Comment by idunnololz** [comment]
Will be added in v1.14.0: https://lemmy.world/post/7391022
