### ISSUE TITLE
Caching for up/downvotes is a little bit too aggressive

### ISSUE THREAD

**Issue by oscarnylander** [idunnololz/summit-for-lemmy#11]
Hi! First off, thanks for a great app. I know that you've spoken against making the source code open, but should you change your mind, know that I'm willing to make code contributions to address issues as I see them.

On to the observed issue:

I've noticed that the caching for up and downvotes is a bit aggressive - consider the following scenario:

1. I navigate to the user detail screen for my user
2. I issue a pull-to-refresh on this screen
3. I observe the number of up and downvotes on this screen

What I expect to see is the most recent count of up and downvotes for any given post or comment in this list.

What I actually see is a cached variant of this data, one that may be stale. The staleness can be proved by either checking an alternative source (such as a Lemmy website), or by issuing an up or downvote and then undoing this action. When performing this action, the cache appears to get invalided, and the value updates to its actual count, which may differ by tens or even hundreds of votes.

Thanks again for a great app.

**Comment by idunnololz** [comment]
This will be fixed in v1.14.0: https://lemmy.world/post/7391022

**Comment by oscarnylander** [comment]
This issue still seems to be present, unfortunately. Perhaps a regression?
