### ISSUE TITLE
Allow 'concatenative'-style paging

### ISSUE THREAD

**Issue by oscarnylander** [idunnololz/summit-for-lemmy#14]
I'm using, and enjoying, the paging option for browsing communities. It works relatively well, but one point that is slightly painful is trying to browse between pages, especially if you want to move very fast backwards in pages. I think it could be nice to add 'concatenative'-style paging, where requesting the next page concatenates the items of the new page to the end of the currently active list, perhaps with a separator item showing where the new page starts. This way, pages can be navigated through quicker by just increasing the speed of scrolling.

**Comment by idunnololz** [comment]
What would be the difference between this and infinite scrolling? The app already supports infinite scrolling.

**Comment by oscarnylander** [comment]
The difference would be that the user still has natural exit points where they can disengage from the list, while infinite scrolling encourages 'unbounded consumption'.

**Comment by idunnololz** [comment]
I don't think I understand the request. Would it be ok if I just added page indicators to infinite scrolling? Eg. whenever a "page" loads, you will see a break, maybe that says "Page X" so you can tell what page you're on.

**Comment by oscarnylander** [comment]
To illustrate:

Today, when requesting a new page, the new page replaces all of the previous items, much like the pages of a book. You can go back and forth between the pages.

The suggested way would be something in-between endless scrolling and paging - requesting a new page would append the next 20 or so items to the bottom of the list, making the list longer. An indicator of where the new page begins would also be a pleasant addition.

I'd be able to illustrate even better if I was on a computer and could draw it, but I'm unfortunately not able to for a while.

Also, thanks for working on these issues! Very nice of you 🙂

**Comment by oscarnylander** [comment]
The key is to let the user consciously choose between getting the next page or not, by the way - the slightly negative thing about endless scrolls is how they don't provide UX off-ramps from the experience and hence encourage higher amounts of consumption

**Comment by idunnololz** [comment]
I think I understand. I will add an option to toggle auto-loading when using Infinity.

**Comment by idunnololz** [comment]
This will be added in v1.14.0: https://lemmy.world/post/7391022.

Page indicators will also be added.
