### ISSUE TITLE
Background in dark mode with material you is too dark

### ISSUE THREAD

**Issue by mstcl** [idunnololz/summit-for-lemmy#16]
I'm using dynamic theming and the normal dark background is almost as dark as the pure black theme option. This isn't the case for other apps, where both the bottom navigation bar and the background uses slightly lighter tones.

Perhaps you could add a calm/high-contrast option for the background like you did for the fonts?

To demonstrate what I mean by Summit's background being significantly darker, see the following screenshots:

## Summit

![Screenshot_20231028-232003](https://github.com/idunnololz/summit-for-lemmy/assets/33115327/997f11c5-0393-4ba0-ae0f-77f19fd0dba3)

## Sync

![IMG_20231028_231941](https://github.com/idunnololz/summit-for-lemmy/assets/33115327/dcfed5b6-11cf-4385-8d82-e3e1fbb5e063)

## Jerboa

![Screenshot_20231028-231708](https://github.com/idunnololz/summit-for-lemmy/assets/33115327/c53fbf45-7a7e-496e-8d46-e0895c4fc753)

**Comment by idunnololz** [comment]
This will be fixed in v1.15.0: https://lemmy.world/post/7791793
