### ISSUE TITLE
Highly nested comments start counting from 0 instead of 1

### ISSUE THREAD

**Issue by malijaffri** [idunnololz/summit-for-lemmy#19]
It seems that the nested comment level counter starts counting from 0 instead of 1. This cause a level 14 comment to instead display level 13, for example. 

[Reference post](https://lemmy.ca/post/8820716)

![Screenshot_20231202_101824_com.idunnololz.summit.jpg](https://github.com/idunnololz/summit-for-lemmy/assets/75521399/22283882-45b0-4529-a86f-8bffc10006d1)

![Screenshot_20231202_101850_com.idunnololz.summit.jpg](https://github.com/idunnololz/summit-for-lemmy/assets/75521399/0c45b7e9-834d-40ba-a36e-d19ff14858d3)

**Comment by idunnololz** [comment]
Thanks for reporting this issue. This will be fixed in v1.18.1. https://lemmy.world/post/9206351
