### ISSUE TITLE
Option to hide interaction bar under comments

### ISSUE THREAD

**Issue by CapnHanSolo** [idunnololz/summit-for-lemmy#2]
I like to view comments in a compact form. However In the comments view the interaction bar appears under every comment.
![a1547333-5810-4498-a3b5-400430f765a1](https://github.com/idunnololz/summit-for-lemmy/assets/51058387/c43576cb-9215-4260-acc5-f9be07a2efcd)

An option in the settings to hide the comment interaction bar would be nice. In this situation a long press could be used to activate interaction bar

**Comment by idunnololz** [comment]
Fixed a while ago.
