### ISSUE TITLE
Bug: Tap comment body to collapse doesn't work with action bar always visible

### ISSUE THREAD

**Issue by theboomr** [idunnololz/summit-for-lemmy#3]
Fairly self explanatory, if you have the setting on to always show the action bar under comments, you can't tap on the comment body to collapse it when when the setting for that is turned on.

**Comment by idunnololz** [comment]
This is intentional. The setting is named aptly as well since it says **Always**. If you could hide it it wouldn't be **always** visible.

**Comment by theboomr** [comment]
I think I might've worded the issue poorly. I'm not trying to collapse the action bar by tapping the comment body, I mean that I can't collapse the comment itself by tapping on the comment body.
