### ISSUE TITLE
Enhancement: audio icon in the video player should be inverted 

### ISSUE THREAD

**Issue by Mannivu** [idunnololz/summit-for-lemmy#7]
I really love the new internal video player, but I've noticed that the audio icon is "wrong": when the video is muted the icon is this one
![IMG_20230822_131612](https://github.com/idunnololz/summit-for-lemmy/assets/42747216/20f54818-b7d6-43aa-869b-5883af0728ba)
While when the audio is on the icon is this one
![IMG_20230822_131630](https://github.com/idunnololz/summit-for-lemmy/assets/42747216/bcddde15-c0ee-4a04-a350-b864cf6ec88f)
I think they should be inverted since every other video player has them the opposite way.

**Comment by idunnololz** [comment]
This issue should be fixed now.

**Comment by Mannivu** [comment]
@idunnololz yes, now it's fixed. Thanks!
