### ISSUE TITLE
Weird link behaviour 

### ISSUE THREAD

**Issue by Mannivu** [idunnololz/summit-for-lemmy#8]
I'm not sure what's happening, but links inside posts are sometimes rendered wrong and this make them useless. See [this post](https://feddit.nl/post/2749597) through Summit: when clicking links nothing happens. I'm sure it's Summit related, since in Jerboa this doesn't happen and the post's source code looks fine.

Summit
![Screenshot_2023-09-03-10-49-37-622_com idunnololz summit|250x250](https://github.com/idunnololz/summit-for-lemmy/assets/42747216/8451b8da-6fe8-4334-8682-c8d2317d4342)

Jerboa
![Screenshot_2023-09-03-10-49-50-932_com jerboa|250x250](https://github.com/idunnololz/summit-for-lemmy/assets/42747216/a1a42682-5074-4eda-bedc-a4029942816d)

**Comment by idunnololz** [comment]
Thanks for flagging. This should be fixed in v1.9.0: https://lemmy.world/post/4597075

**Comment by Mannivu** [comment]
@idunnololz not really, it still behaves poorly (the first link work fine, but then the others are broken)
![Screenshot_2023-09-11-19-36-01-832_com idunnololz summit](https://github.com/idunnololz/summit-for-lemmy/assets/42747216/8fa83017-a7ee-47a7-ab05-56731d3964f9)
![Screenshot_2023-09-11-19-36-04-601_com idunnololz summit](https://github.com/idunnololz/summit-for-lemmy/assets/42747216/57f04f57-a283-40d6-8340-ad872eade01e)

**Comment by Mannivu** [comment]
Now it work fine.
